artifact_location: file:C:\Users\vamsh\OneDrive\Pictures\Saved Pictures\Documents\New
  folder (2)\project\majorproject\mlops\tracking/138321225851120278
creation_time: 1762610540460
experiment_id: '138321225851120278'
last_update_time: 1762610540460
lifecycle_stage: active
name: LegalAid_Connect_Matchmaking
